# Generated by Django 5.0.14 on 2025-12-23 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startup_name', models.CharField(blank=True, max_length=255)),
                ('startup_description', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('current_stage', models.CharField(blank=True, choices=[('idea', 'Idea Stage'), ('mvp', 'MVP Development'), ('early_stage', 'Early-Stage'), ('growth', 'Growth Stage'), ('scale_up', 'Scale-Up')], max_length=50)),
                ('business_model', models.TextField(blank=True)),
                ('geographic_focus', models.CharField(blank=True, max_length=255)),
                ('research_goal', models.TextField(blank=True)),
                ('time_range', models.CharField(blank=True, choices=[('1mo', 'Last Month'), ('3mo', 'Last 3 Months'), ('6mo', 'Last 6 Months'), ('1yr', 'Last Year'), ('all', 'All Time')], max_length=50)),
                ('inspiration_sources', models.TextField(blank=True)),
                ('target_description', models.TextField(blank=True)),
                ('extracted_keywords', models.JSONField(blank=True, default=list)),
                ('completion_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('partial', 'Partial'), ('complete', 'Complete')], default='incomplete', max_length=50)),
                ('filled_via', models.CharField(blank=True, choices=[('manual', 'Manual'), ('ai_chat', 'AI Chat'), ('mixed', 'Mixed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='projects.project')),
            ],
            options={
                'db_table': 'project_inputs',
            },
        ),
    ]
