# Generated by Django 5.0.14 on 2025-12-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinput',
            name='ai_generated_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
