# Generated by Django 5.0.14 on 2025-12-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectinput_ai_generated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinput',
            name='current_stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectinput',
            name='time_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
