# Generated by Django 5.0.14 on 2025-12-23 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_category', models.CharField(blank=True, max_length=100)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('storage_path', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='organizations.organization')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-created_at'],
            },
        ),
    ]
