# Generated by Django 5.0.14 on 2025-12-23 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtoken',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='downloadtoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['organization', '-created_at'], name='api_usage_organiz_1fe5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['endpoint', '-created_at'], name='api_usage_endpoin_f846a8_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['user', '-created_at'], name='api_usage_user_id_ff16f2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='audit_logs_organiz_86ff70_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['token'], name='download_to_token_591bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['file'], name='download_to_file_id_7a00ac_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['expires_at'], name='download_to_expires_c00e0a_idx'),
        ),
    ]
