# Generated by Django 5.0.14 on 2026-01-04 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('num_companies', models.IntegerField(default=50, help_text='Number of companies to scrape for this keyword')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority keywords are processed first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_processed', models.IntegerField(default=0)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='running', max_length=20)),
                ('companies_found', models.IntegerField(default=0)),
                ('companies_scraped', models.IntegerField(default=0)),
                ('companies_skipped', models.IntegerField(default=0, help_text='Companies skipped due to freshness')),
                ('worker_id', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='admin_panel.enrichmentkeyword')),
            ],
            options={
                'verbose_name_plural': 'Enrichment histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paused', models.BooleanField(default=False, help_text='When True, no new enrichment tasks will be dispatched')),
                ('days_threshold', models.IntegerField(default=180, help_text='Skip companies scraped within this many days')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Enrichment settings',
            },
        ),
    ]
