# Generated by Django 5.0.14 on 2025-12-23 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('crunchbase', 'Crunchbase Analysis'), ('tracxn', 'Tracxn Analysis'), ('social', 'Social Analysis'), ('pitch_deck', 'Pitch Deck')], max_length=50)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('outdated', 'Outdated')], default='not_started', max_length=50)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('html_content', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('inputs_hash', models.CharField(blank=True, max_length=32)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('html_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='files.file')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['report_type'],
                'unique_together': {('project', 'report_type')},
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('html_content', models.TextField()),
                ('data_snapshot', models.JSONField(default=dict)),
                ('changes_summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('html_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_versions', to='files.file')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reports.report')),
            ],
            options={
                'db_table': 'report_versions',
                'ordering': ['-version_number'],
                'unique_together': {('report', 'version_number')},
            },
        ),
    ]
