# Generated by Django 5.0.14 on 2025-12-25 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnalysisSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('company_overview', 'Company Overview'), ('tech_product', 'Technology & Product'), ('market_demand', 'Market Demand & Web Insights'), ('competitor', 'Competitor Identification'), ('market_funding', 'Market & Funding Insights'), ('growth_potential', 'Growth Potential'), ('swot', 'SWOT Analysis'), ('tech_product_summary', 'Tech & Product Summary'), ('market_demand_summary', 'Market Demand Summary'), ('competitor_summary', 'Competitor Summary'), ('market_funding_summary', 'Funding Summary'), ('growth_potential_summary', 'Growth Summary'), ('swot_summary', 'SWOT Summary')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('content_markdown', models.TextField()),
                ('content_html', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sections', to='reports.report')),
            ],
            options={
                'db_table': 'report_analysis_sections',
                'ordering': ['order', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportProgressStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('step_key', models.CharField(max_length=100)),
                ('step_name', models.CharField(max_length=255)),
                ('step_description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_steps', to='reports.report')),
            ],
            options={
                'db_table': 'report_progress_steps',
                'ordering': ['step_number'],
                'unique_together': {('report', 'step_key')},
            },
        ),
    ]
