# Generated by Django 5.0.14 on 2025-12-25 19:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportanalysissection_reportprogressstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTimingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(db_index=True, max_length=50)),
                ('step_key', models.CharField(db_index=True, max_length=100)),
                ('duration_seconds', models.FloatField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'step_timing_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'step_key', '-created_at'], name='step_timing_report__86ccfe_idx')],
            },
        ),
    ]
