# Generated by Django 5.0.14 on 2025-12-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_step_timing_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprogressstep',
            name='details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
