# Generated by Django 5.0.14 on 2026-01-05 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_details_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRawData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('report_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data_versions', to='reports.report')),
            ],
            options={
                'db_table': 'report_raw_data',
                'ordering': ['-version'],
                'unique_together': {('report', 'version', 'report_type')},
            },
        ),
    ]
