# Generated by Django 5.0.14 on 2026-01-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('quick_report', 'Quick Report'), ('crunchbase', 'Crunchbase Analysis'), ('tracxn', 'Tracxn Analysis'), ('social', 'Social Analysis'), ('verdict', 'Verdict Analysis'), ('pitch_deck', 'Pitch Deck')], max_length=50),
        ),
    ]
