# Generated by Django 5.0.14 on 2026-01-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_summarization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_project_ba45c5_idx',
            old_name='chat_msg_proj_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_project_e225b7_idx',
            old_name='chat_msg_proj_sum_idx',
        ),
    ]
